name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build & typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Setup bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: 1.2.21

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: Extract version
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Build
        run: bun install --frozen-lockfile && bun run build

      - name: Package
        run: bun pm pack

      - name: Publish
        run: npm publish surrealdb-mastra-ai-${VERSION}.tgz --access public
